// <auto-generated />
using System;
using Challenge.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Challenge.Infrastructure.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20240303193541_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Challenge.Domain.Entities.ProductEntity", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierCNPJ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "ProductEntity 1",
                            ExpiryDate = new DateTime(2025, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(817),
                            IsActive = true,
                            ManufactureDate = new DateTime(2024, 3, 3, 16, 35, 40, 853, DateTimeKind.Local).AddTicks(4735),
                            SupplierCNPJ = "12.345.678/0001-90",
                            SupplierCode = "1",
                            SupplierDescription = "Supplier 1"
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "ProductEntity 2",
                            ExpiryDate = new DateTime(2025, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4724),
                            IsActive = true,
                            ManufactureDate = new DateTime(2024, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4717),
                            SupplierCNPJ = "98.765.432/0001-09",
                            SupplierCode = "2",
                            SupplierDescription = "Supplier 2"
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "ProductEntity 3",
                            ExpiryDate = new DateTime(2025, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4740),
                            IsActive = true,
                            ManufactureDate = new DateTime(2024, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4739),
                            SupplierCNPJ = "12.345.678/0001-90",
                            SupplierCode = "3",
                            SupplierDescription = "Supplier 3"
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "ProductEntity 4",
                            ExpiryDate = new DateTime(2025, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4744),
                            IsActive = true,
                            ManufactureDate = new DateTime(2024, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4742),
                            SupplierCNPJ = "98.765.432/0001-09",
                            SupplierCode = "4",
                            SupplierDescription = "Supplier 4"
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "ProductEntity 5",
                            ExpiryDate = new DateTime(2025, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4747),
                            IsActive = true,
                            ManufactureDate = new DateTime(2024, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4746),
                            SupplierCNPJ = "12.345.678/0001-90",
                            SupplierCode = "5",
                            SupplierDescription = "Supplier 5"
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "ProductEntity 6",
                            ExpiryDate = new DateTime(2025, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4751),
                            IsActive = true,
                            ManufactureDate = new DateTime(2024, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4749),
                            SupplierCNPJ = "98.765.432/0001-09",
                            SupplierCode = "6",
                            SupplierDescription = "Supplier 6"
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "ProductEntity 7",
                            ExpiryDate = new DateTime(2025, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4754),
                            IsActive = true,
                            ManufactureDate = new DateTime(2024, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4753),
                            SupplierCNPJ = "12.345.678/0001-90",
                            SupplierCode = "7",
                            SupplierDescription = "Supplier 7"
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "ProductEntity 8",
                            ExpiryDate = new DateTime(2025, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4757),
                            IsActive = true,
                            ManufactureDate = new DateTime(2024, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4756),
                            SupplierCNPJ = "98.765.432/0001-09",
                            SupplierCode = "8",
                            SupplierDescription = "Supplier 8"
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "ProductEntity 9",
                            ExpiryDate = new DateTime(2025, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4761),
                            IsActive = true,
                            ManufactureDate = new DateTime(2024, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4760),
                            SupplierCNPJ = "12.345.678/0001-90",
                            SupplierCode = "9",
                            SupplierDescription = "Supplier 9"
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "ProductEntity 10",
                            ExpiryDate = new DateTime(2025, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4764),
                            IsActive = true,
                            ManufactureDate = new DateTime(2024, 3, 3, 16, 35, 40, 855, DateTimeKind.Local).AddTicks(4763),
                            SupplierCNPJ = "98.765.432/0001-09",
                            SupplierCode = "10",
                            SupplierDescription = "Supplier 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
